model:
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 500
    feature_size: 56
    n_layer_enc: 4
    n_layer_dec: 6
    d_model: 128
    timesteps: 500
    sampling_timesteps: 500
    loss_type: 'l1'
    beta_schedule: 'cosine'
    n_heads: 8
    mlp_hidden_times: 4
    attn_pd: 0.1
    resid_pd: 0.1
    kernel_size: 7
    padding_size: 3

solver:
  base_lr: 1.0e-5
  max_epochs: 20000
  results_folder: ./Result/Checkpoints_jumping
  gradient_accumulate_every: 2
  save_cycle: 800
  ema:
    decay: 0.995
    update_interval: 10
  
  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 3000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 5.0e-4
      warmup: 500 
      verbose: False

dataloader:
  train_dataset:
    target: Utils.Data_utils.csi_dataset.CustomDataset
    params:
      name: jumping
      proportion: 0.95  # Set to rate < 1 if training conditional generation
      data_root: ./Data/datasets/jumping.csv
      window: 500  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train

  test_dataset:
    target: Utils.Data_utils.csi_dataset.CustomDataset
    params:
      name: jumping
      proportion: 0.9  # rate
      data_root: ./Data/datasets/jumping.csv
      window: 500  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: test
      style: separate
      distribution: geometric
    coefficient: 1.0e-2
    step_size: 5.0e-2
    sampling_steps: 250

  batch_size: 64
  sample_size: 512
  shuffle: True